
package viewInterna;

import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JRootPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author miri
 */
public class ViewProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame
     */
    public ViewProductos() {
        initComponents();
    }

    public JButton getjButtonBuscarPro() {
        return jButtonBuscarPro;
    }

    public void setjButtonBuscarPro(JButton jButtonBuscarPro) {
        this.jButtonBuscarPro = jButtonBuscarPro;
    }

    public JButton getjButtonCancelarPro() {
        return jButtonCancelarPro;
    }

    public void setjButtonCancelarPro(JButton jButtonCancelarPro) {
        this.jButtonCancelarPro = jButtonCancelarPro;
    }

    public JButton getjButtonCrearPro() {
        return jButtonCrearPro;
    }

    public void setjButtonCrearPro(JButton jButtonCrearPro) {
        this.jButtonCrearPro = jButtonCrearPro;
    }

    public JButton getjButtonEditarPro() {
        return jButtonEditarPro;
    }

    public void setjButtonEditarPro(JButton jButtonEditarPro) {
        this.jButtonEditarPro = jButtonEditarPro;
    }

    public JButton getjButtonEliminarPro() {
        return jButtonEliminarPro;
    }

    public void setjButtonEliminarPro(JButton jButtonEliminarPro) {
        this.jButtonEliminarPro = jButtonEliminarPro;
    }

    public JButton getjButtonImprimirPro() {
        return jButtonImprimirPro;
    }

    public void setjButtonImprimirPro(JButton jButtonImprimirPro) {
        this.jButtonImprimirPro = jButtonImprimirPro;
    }

    public JButton getjButtonLimpiarPro() {
        return jButtonLimpiarPro;
    }

    public void setjButtonLimpiarPro(JButton jButtonLimpiarPro) {
        this.jButtonLimpiarPro = jButtonLimpiarPro;
    }

    public JButton getjButtonLimpiarProB() {
        return jButtonLimpiarProB;
    }

    public void setjButtonLimpiarProB(JButton jButtonLimpiarProB) {
        this.jButtonLimpiarProB = jButtonLimpiarProB;
    }

    public JCheckBox getjCheckBoxMostrarT() {
        return jCheckBoxMostrarT;
    }

    public void setjCheckBoxMostrarT(JCheckBox jCheckBoxMostrarT) {
        this.jCheckBoxMostrarT = jCheckBoxMostrarT;
    }

    public JTextField getjTextFieldBusquedaPro() {
        return jTextFieldBusquedaPro;
    }

    public void setjTextFieldBusquedaPro(JTextField jTextFieldBusquedaPro) {
        this.jTextFieldBusquedaPro = jTextFieldBusquedaPro;
    }

    public JSpinner getjSpinnerCantidad() {
        return jSpinnerCantidad;
    }

    public void setjSpinnerCantidad(JSpinner jSpinnerCantidad) {
        this.jSpinnerCantidad = jSpinnerCantidad;
    }

    
    public JTextField getjTextFieldNombrePro() {
        return jTextFieldNombrePro;
    }

    public void setjTextFieldNombrePro(JTextField jTextFieldNombrePro) {
        this.jTextFieldNombrePro = jTextFieldNombrePro;
    }

    public JTextField getjTextFieldPrecioPro() {
        return jTextFieldPrecioPro;
    }

    public void setjTextFieldPrecioPro(JTextField jTextFieldPrecioPro) {
        this.jTextFieldPrecioPro = jTextFieldPrecioPro;
    }

    public JTable getjTableDatosProductos() {
        return jTableDatosProductos;
    }

    public void setjTableDatosProductos(JTable jTableDatosProductos) {
        this.jTableDatosProductos = jTableDatosProductos;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDatosProductos = new javax.swing.JTable();
        jButtonCancelarPro = new javax.swing.JButton();
        jButtonImprimirPro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPrecioPro = new javax.swing.JTextField();
        jButtonCrearPro = new javax.swing.JButton();
        jButtonEditarPro = new javax.swing.JButton();
        jButtonLimpiarPro = new javax.swing.JButton();
        jButtonEliminarPro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jTextFieldNombrePro = new javax.swing.JTextField();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBusquedaPro = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuscarPro = new javax.swing.JButton();
        jButtonLimpiarProB = new javax.swing.JButton();
        jCheckBoxMostrarT = new javax.swing.JCheckBox();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(237, 242, 244));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(1030, 577));

        jPanel2.setBackground(new java.awt.Color(237, 242, 244));

        jPanel5.setBackground(new java.awt.Color(237, 242, 244));
        jPanel5.setPreferredSize(new java.awt.Dimension(640, 344));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDatosProductos.setBackground(new java.awt.Color(204, 218, 209));
        jTableDatosProductos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableDatosProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableDatosProductos);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 50, 520, 160));

        jButtonCancelarPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonCancelarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/cross.gif"))); // NOI18N
        jButtonCancelarPro.setText("Cancelar");
        jButtonCancelarPro.setBorder(null);
        jPanel5.add(jButtonCancelarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 90, 35));

        jButtonImprimirPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonImprimirPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/imprimir.png"))); // NOI18N
        jButtonImprimirPro.setBorder(null);
        jPanel5.add(jButtonImprimirPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 39, 35));

        jButton2.setBackground(new java.awt.Color(237, 242, 244));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/boxes.png"))); // NOI18N
        jButton2.setBorder(null);
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 30, 35));

        jSeparator20.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator20.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel5.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 610, 10));

        jSeparator21.setBackground(new java.awt.Color(0, 29, 61));
        jPanel5.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 28, 465, 10));

        jSeparator22.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 250));

        jSeparator23.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 10, 250));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Lista de Productos");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(237, 242, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/persona.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Precio:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cantidad:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jTextFieldPrecioPro.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldPrecioPro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPrecioPro.setBorder(null);
        jTextFieldPrecioPro.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldPrecioPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, -1));

        jButtonCrearPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonCrearPro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonCrearPro.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCrearPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/agregar.png"))); // NOI18N
        jButtonCrearPro.setBorder(null);
        jPanel4.add(jButtonCrearPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 40, 40));

        jButtonEditarPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonEditarPro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonEditarPro.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEditarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/editar.png"))); // NOI18N
        jButtonEditarPro.setBorder(null);
        jPanel4.add(jButtonEditarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        jButtonLimpiarPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonLimpiarPro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonLimpiarPro.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/limpiar.png"))); // NOI18N
        jButtonLimpiarPro.setBorder(null);
        jPanel4.add(jButtonLimpiarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 50, 40));

        jButtonEliminarPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonEliminarPro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonEliminarPro.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEliminarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/eliminar.png"))); // NOI18N
        jButtonEliminarPro.setBorder(null);
        jPanel4.add(jButtonEliminarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 50, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 260, 10));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 260, 10));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 260, 10));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Administración de Productos");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 29, 61));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 10));

        jSeparator18.setBackground(new java.awt.Color(0, 29, 61));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 360, 10));

        jSeparator19.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 450));

        jSeparator27.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 10, 460));

        jTextFieldNombrePro.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldNombrePro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNombrePro.setBorder(null);
        jTextFieldNombrePro.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldNombrePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 260, -1));

        jSpinnerCantidad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerCantidad.setBorder(null);
        jPanel4.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, 30));

        jPanel1.setBackground(new java.awt.Color(237, 242, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Búsqueda de Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Opciones de Búsqueda");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 59, -1, -1));

        jTextFieldBusquedaPro.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldBusquedaPro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldBusquedaPro.setBorder(null);
        jTextFieldBusquedaPro.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel1.add(jTextFieldBusquedaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, 205, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 139, 205, 10));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Criterio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 88, -1, -1));

        jButtonBuscarPro.setBackground(new java.awt.Color(237, 242, 244));
        jButtonBuscarPro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonBuscarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/buscar.png"))); // NOI18N
        jButtonBuscarPro.setBorder(null);
        jPanel1.add(jButtonBuscarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 108, 38, 37));

        jButtonLimpiarProB.setBackground(new java.awt.Color(237, 242, 244));
        jButtonLimpiarProB.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonLimpiarProB.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiarProB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/limpiar.png"))); // NOI18N
        jButtonLimpiarProB.setBorder(null);
        jButtonLimpiarProB.setPreferredSize(new java.awt.Dimension(25, 28));
        jPanel1.add(jButtonLimpiarProB, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 108, 43, 37));

        jCheckBoxMostrarT.setBackground(new java.awt.Color(237, 242, 244));
        jCheckBoxMostrarT.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBoxMostrarT.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxMostrarT.setText("Mostrar Todo");
        jCheckBoxMostrarT.setBorder(null);
        jPanel1.add(jCheckBoxMostrarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 108, -1, 37));

        jSeparator15.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 10));

        jSeparator16.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 262, 10));

        jSeparator24.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 14, 160));

        jSeparator26.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 14, 160));

        jSeparator25.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 610, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarPro;
    private javax.swing.JButton jButtonCancelarPro;
    private javax.swing.JButton jButtonCrearPro;
    private javax.swing.JButton jButtonEditarPro;
    private javax.swing.JButton jButtonEliminarPro;
    private javax.swing.JButton jButtonImprimirPro;
    private javax.swing.JButton jButtonLimpiarPro;
    private javax.swing.JButton jButtonLimpiarProB;
    private javax.swing.JCheckBox jCheckBoxMostrarT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableDatosProductos;
    private javax.swing.JTextField jTextFieldBusquedaPro;
    private javax.swing.JTextField jTextFieldNombrePro;
    private javax.swing.JTextField jTextFieldPrecioPro;
    // End of variables declaration//GEN-END:variables
}
