
package viewInterna;

import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author miri
 */
public class ViewUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame
     */
    public ViewUsuarios() {
        initComponents();
    }

    public JButton getjButtonBuscarUsu() {
        return jButtonBuscarUsu;
    }

    public JButton getjButtonReportarUs() {
        return jButtonReportarUs;
    }

    public void setjButtonReportarUs(JButton jButtonReportarUs) {
        this.jButtonReportarUs = jButtonReportarUs;
    }

    public void setjButtonBuscarUsu(JButton jButtonBuscarUsu) {
        this.jButtonBuscarUsu = jButtonBuscarUsu;
    }

    public JButton getjButtonCancelarUsu() {
        return jButtonCancelarUsu;
    }

    public void setjButtonCancelarUsu(JButton jButtonCancelarUsu) {
        this.jButtonCancelarUsu = jButtonCancelarUsu;
    }

    public JButton getjButtonCrearUsu() {
        return jButtonCrearUsu;
    }

    public void setjButtonCrearUsu(JButton jButtonCrearUsu) {
        this.jButtonCrearUsu = jButtonCrearUsu;
    }

    public JButton getjButtonEditarUsu() {
        return jButtonEditarUsu;
    }

    public void setjButtonEditarUsu(JButton jButtonEditarUsu) {
        this.jButtonEditarUsu = jButtonEditarUsu;
    }

    public JButton getjButtonEliminarUsu() {
        return jButtonEliminarUsu;
    }

    public void setjButtonEliminarUsu(JButton jButtonEliminarUsu) {
        this.jButtonEliminarUsu = jButtonEliminarUsu;
    }

    public JButton getjButtonImprimirUsu() {
        return jButtonImprimirUsu;
    }

    public void setjButtonImprimirUsu(JButton jButtonImprimirUsu) {
        this.jButtonImprimirUsu = jButtonImprimirUsu;
    }

    public JButton getjButtonLimpiarUsu() {
        return jButtonLimpiarUsu;
    }

    public void setjButtonLimpiarUsu(JButton jButtonLimpiarUsu) {
        this.jButtonLimpiarUsu = jButtonLimpiarUsu;
    }

    public JButton getjButtonLimpiarUsuB() {
        return jButtonLimpiarUsuB;
    }

    public void setjButtonLimpiarUsuB(JButton jButtonLimpiarUsuB) {
        this.jButtonLimpiarUsuB = jButtonLimpiarUsuB;
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBoxMostrarTU;
    }

    public void setjCheckBox1(JCheckBox jCheckBox1) {
        this.jCheckBoxMostrarTU = jCheckBox1;
    }

    public JPasswordField getjPasswordFieldClave() {
        return jPasswordFieldClave;
    }

    public void setjPasswordFieldClave(JPasswordField jPasswordFieldClave) {
        this.jPasswordFieldClave = jPasswordFieldClave;
    }

    public JTable getjTableDatosUsuarios() {
        return jTableDatosUsuarios;
    }

    public void setjTableDatosUsuarios(JTable jTableDatosUsuarios) {
        this.jTableDatosUsuarios = jTableDatosUsuarios;
    }

    public JTextField getjTextFieldBusquedaUsus() {
        return jTextFieldBusquedaUsus;
    }

    public void setjTextFieldBusquedaUsus(JTextField jTextFieldBusquedaUsus) {
        this.jTextFieldBusquedaUsus = jTextFieldBusquedaUsus;
    }

    public JComboBox<String> getjComboBoxPersonasUsu() {
        return jComboBoxPersonasUsu;
    }

    public void setjComboBoxPersonasUsu(JComboBox<String> jComboBoxPersonasUsu) {
        this.jComboBoxPersonasUsu = jComboBoxPersonasUsu;
    }


    public JTextField getjTextFieldUsuario() {
        return jTextFieldUsuario;
    }

    public void setjTextFieldUsuario(JTextField jTextFieldUsuario) {
        this.jTextFieldUsuario = jTextFieldUsuario;
    }

    public JCheckBox getjCheckBoxMostrarTU() {
        return jCheckBoxMostrarTU;
    }

    public void setjCheckBoxMostrarTU(JCheckBox jCheckBoxMostrarTU) {
        this.jCheckBoxMostrarTU = jCheckBoxMostrarTU;
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDatosUsuarios = new javax.swing.JTable();
        jButtonCancelarUsu = new javax.swing.JButton();
        jButtonImprimirUsu = new javax.swing.JButton();
        jButtonReportarUs = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonCrearUsu = new javax.swing.JButton();
        jButtonEditarUsu = new javax.swing.JButton();
        jButtonLimpiarUsu = new javax.swing.JButton();
        jButtonEliminarUsu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jPasswordFieldClave = new javax.swing.JPasswordField();
        jComboBoxPersonasUsu = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBusquedaUsus = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuscarUsu = new javax.swing.JButton();
        jButtonLimpiarUsuB = new javax.swing.JButton();
        jCheckBoxMostrarTU = new javax.swing.JCheckBox();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(237, 242, 244));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(1030, 577));

        jPanel2.setBackground(new java.awt.Color(237, 242, 244));

        jPanel5.setBackground(new java.awt.Color(237, 242, 244));
        jPanel5.setPreferredSize(new java.awt.Dimension(640, 344));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDatosUsuarios.setBackground(new java.awt.Color(204, 218, 209));
        jTableDatosUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTableDatosUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableDatosUsuarios);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 50, 510, 160));

        jButtonCancelarUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonCancelarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/cross.gif"))); // NOI18N
        jButtonCancelarUsu.setText("Cancelar");
        jButtonCancelarUsu.setBorder(null);
        jPanel5.add(jButtonCancelarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 220, 80, 35));

        jButtonImprimirUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonImprimirUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/imprimir.png"))); // NOI18N
        jButtonImprimirUsu.setBorder(null);
        jPanel5.add(jButtonImprimirUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 39, 35));

        jButtonReportarUs.setBackground(new java.awt.Color(237, 242, 244));
        jButtonReportarUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/boxes.png"))); // NOI18N
        jButtonReportarUs.setBorder(null);
        jPanel5.add(jButtonReportarUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 30, 35));

        jSeparator20.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator20.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel5.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 610, 10));

        jSeparator21.setBackground(new java.awt.Color(0, 29, 61));
        jPanel5.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 28, 465, 10));

        jSeparator22.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 250));

        jSeparator23.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 10, 250));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Lista de Usuarios");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(237, 242, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/persona.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Usuario:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contraseña:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ID Persona:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldUsuario.setToolTipText("Utilice letras y numeros, pero sin carateres especiales");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 260, -1));

        jButtonCrearUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonCrearUsu.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonCrearUsu.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCrearUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/agregar.png"))); // NOI18N
        jButtonCrearUsu.setBorder(null);
        jPanel4.add(jButtonCrearUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 40, 40));

        jButtonEditarUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonEditarUsu.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonEditarUsu.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEditarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/editar.png"))); // NOI18N
        jButtonEditarUsu.setBorder(null);
        jPanel4.add(jButtonEditarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        jButtonLimpiarUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonLimpiarUsu.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonLimpiarUsu.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/limpiar.png"))); // NOI18N
        jButtonLimpiarUsu.setBorder(null);
        jPanel4.add(jButtonLimpiarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 50, 40));

        jButtonEliminarUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonEliminarUsu.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonEliminarUsu.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEliminarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/eliminar.png"))); // NOI18N
        jButtonEliminarUsu.setBorder(null);
        jPanel4.add(jButtonEliminarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 50, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 260, 10));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 260, 10));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 260, 10));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Administración de Usuarios");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 29, 61));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 10));

        jSeparator18.setBackground(new java.awt.Color(0, 29, 61));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 360, 10));

        jSeparator19.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 450));

        jSeparator27.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 10, 460));

        jPasswordFieldClave.setBackground(new java.awt.Color(237, 242, 244));
        jPasswordFieldClave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordFieldClave.setToolTipText("min 1 letra mayus | min 1 letra minus | min 1 caract especial | min 1 numero | minimo 8 caracteres max 20");
        jPasswordFieldClave.setBorder(null);
        jPanel4.add(jPasswordFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 260, 20));

        jComboBoxPersonasUsu.setBackground(new java.awt.Color(237, 242, 244));
        jComboBoxPersonasUsu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxPersonasUsu.setBorder(null);
        jPanel4.add(jComboBoxPersonasUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, -1));

        jPanel1.setBackground(new java.awt.Color(237, 242, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Búsqueda de Usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Opciones de Búsqueda");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 59, -1, -1));

        jTextFieldBusquedaUsus.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldBusquedaUsus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldBusquedaUsus.setBorder(null);
        jTextFieldBusquedaUsus.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel1.add(jTextFieldBusquedaUsus, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, 205, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 139, 205, 10));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Criterio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 88, -1, -1));

        jButtonBuscarUsu.setBackground(new java.awt.Color(237, 242, 244));
        jButtonBuscarUsu.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonBuscarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/buscar.png"))); // NOI18N
        jButtonBuscarUsu.setBorder(null);
        jPanel1.add(jButtonBuscarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 108, 38, 37));

        jButtonLimpiarUsuB.setBackground(new java.awt.Color(237, 242, 244));
        jButtonLimpiarUsuB.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonLimpiarUsuB.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiarUsuB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/limpiar.png"))); // NOI18N
        jButtonLimpiarUsuB.setBorder(null);
        jButtonLimpiarUsuB.setPreferredSize(new java.awt.Dimension(25, 28));
        jPanel1.add(jButtonLimpiarUsuB, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 108, 43, 37));

        jCheckBoxMostrarTU.setBackground(new java.awt.Color(237, 242, 244));
        jCheckBoxMostrarTU.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBoxMostrarTU.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxMostrarTU.setText("Mostrar Todo");
        jCheckBoxMostrarTU.setBorder(null);
        jPanel1.add(jCheckBoxMostrarTU, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 108, -1, 37));

        jSeparator15.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 10));

        jSeparator16.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 262, 10));

        jSeparator24.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 14, 160));

        jSeparator26.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 14, 160));

        jSeparator25.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 610, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarUsu;
    private javax.swing.JButton jButtonCancelarUsu;
    private javax.swing.JButton jButtonCrearUsu;
    private javax.swing.JButton jButtonEditarUsu;
    private javax.swing.JButton jButtonEliminarUsu;
    private javax.swing.JButton jButtonImprimirUsu;
    private javax.swing.JButton jButtonLimpiarUsu;
    private javax.swing.JButton jButtonLimpiarUsuB;
    private javax.swing.JButton jButtonReportarUs;
    private javax.swing.JCheckBox jCheckBoxMostrarTU;
    private javax.swing.JComboBox<String> jComboBoxPersonasUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTableDatosUsuarios;
    private javax.swing.JTextField jTextFieldBusquedaUsus;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
