
package viewInterna;

import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author miri
 */
public class ViewPersonas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame
     */
    public ViewPersonas() {
        initComponents();
    }

    public JButton getjButtonCancelarPersona() {
        return jButtonCancelarPersona;
    }

    public void setjButtonCancelarPersona(JButton jButtonCancelarPersona) {
        this.jButtonCancelarPersona = jButtonCancelarPersona;
    }

    public JButton getjButtonLimpiarPer1() {
        return jButtonLimpiarPer1;
    }

    public void setjButtonLimpiarPer1(JButton jButtonLimpiarPer1) {
        this.jButtonLimpiarPer1 = jButtonLimpiarPer1;
    }

    public JTextField getjTextFieldBusquedaPer() {
        return jTextFieldBusquedaPer;
    }

    public void setjTextFieldBusquedaPer(JTextField jTextFieldBusquedaPer) {
        this.jTextFieldBusquedaPer = jTextFieldBusquedaPer;
    }

    public JButton getjButtonCrearPer() {
        return jButtonCrearPer;
    }

    public void setjButtonCrearPer(JButton jButtonCrearPer) {
        this.jButtonCrearPer = jButtonCrearPer;
    }

    public JButton getjButtonEditarPer() {
        return jButtonEditarPer;
    }

    public void setjButtonEditarPer(JButton jButtonEditarPer) {
        this.jButtonEditarPer = jButtonEditarPer;
    }

    public JButton getjButtonEliminarPer() {
        return jButtonEliminarPer;
    }

    public void setjButtonEliminarPer(JButton jButtonEliminarPer) {
        this.jButtonEliminarPer = jButtonEliminarPer;
    }

    public JButton getjButtonLimpiarPer() {
        return jButtonLimpiarPer;
    }

    public void setjButtonLimpiarPer(JButton jButtonLimpiarPer) {
        this.jButtonLimpiarPer = jButtonLimpiarPer;
    }

    public JTable getjTableDatosPersonas() {
        return jTableDatosPersonas;
    }

    public void setjTableDatosPersonas(JTable jTableDatosPersonas) {
        this.jTableDatosPersonas = jTableDatosPersonas;
    }

    public JTextField getjTextFieldApellidos() {
        return jTextFieldApellidos;
    }

    public void setjTextFieldApellidos(JTextField jTextFieldApellidos) {
        this.jTextFieldApellidos = jTextFieldApellidos;
    }

    public JTextField getjTextFieldCedula() {
        return jTextFieldCedula;
    }

    public void setjTextFieldCedula(JTextField jTextFieldCedula) {
        this.jTextFieldCedula = jTextFieldCedula;
    }

    public JTextField getjTextFieldCelular() {
        return jTextFieldCelular;
    }

    public void setjTextFieldCelular(JTextField jTextFieldCelular) {
        this.jTextFieldCelular = jTextFieldCelular;
    }

    public JTextField getjTextFieldCorreo() {
        return jTextFieldCorreo;
    }

    public void setjTextFieldCorreo(JTextField jTextFieldCorreo) {
        this.jTextFieldCorreo = jTextFieldCorreo;
    }

    public JTextField getjTextFieldDireccion() {
        return jTextFieldDireccion;
    }

    public void setjTextFieldDireccion(JTextField jTextFieldDireccion) {
        this.jTextFieldDireccion = jTextFieldDireccion;
    }

    public JTextField getjTextFieldNombres() {
        return jTextFieldNombres;
    }

    public void setjTextFieldNombres(JTextField jTextFieldNombres) {
        this.jTextFieldNombres = jTextFieldNombres;
    }

    public JButton getjButtonBuscarPer() {
        return jButtonBuscarPer;
    }

    public void setjButtonBuscarPer(JButton jButtonBuscarPer) {
        this.jButtonBuscarPer = jButtonBuscarPer;
    }

    public JCheckBox getjCheckBoxMostrarTP() {
        return jCheckBoxMostrarTP;
    }

    public void setjCheckBoxMostrarTP(JCheckBox jCheckBoxMostrarTP) {
        this.jCheckBoxMostrarTP = jCheckBoxMostrarTP;
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDatosPersonas = new javax.swing.JTable();
        jButtonCancelarPersona = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jButtonCrearPer = new javax.swing.JButton();
        jButtonEditarPer = new javax.swing.JButton();
        jButtonLimpiarPer = new javax.swing.JButton();
        jButtonEliminarPer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBusquedaPer = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuscarPer = new javax.swing.JButton();
        jButtonLimpiarPer1 = new javax.swing.JButton();
        jCheckBoxMostrarTP = new javax.swing.JCheckBox();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(237, 242, 244));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(1030, 577));

        jPanel2.setBackground(new java.awt.Color(237, 242, 244));

        jPanel5.setBackground(new java.awt.Color(237, 242, 244));
        jPanel5.setPreferredSize(new java.awt.Dimension(640, 344));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDatosPersonas.setBackground(new java.awt.Color(204, 218, 209));
        jTableDatosPersonas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTableDatosPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableDatosPersonas);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 50, 536, 212));

        jButtonCancelarPersona.setBackground(new java.awt.Color(237, 242, 244));
        jButtonCancelarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/cross.gif"))); // NOI18N
        jButtonCancelarPersona.setText("Cancelar");
        jButtonCancelarPersona.setBorder(null);
        jPanel5.add(jButtonCancelarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 274, 90, 35));

        jButton1.setBackground(new java.awt.Color(237, 242, 244));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/imprimir.png"))); // NOI18N
        jButton1.setBorder(null);
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 274, 39, 35));

        jButton2.setBackground(new java.awt.Color(237, 242, 244));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/boxes.png"))); // NOI18N
        jButton2.setBorder(null);
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 274, 30, 35));

        jSeparator20.setBackground(new java.awt.Color(0, 29, 61));
        jPanel5.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 610, 10));

        jSeparator21.setBackground(new java.awt.Color(0, 29, 61));
        jPanel5.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 460, 10));

        jSeparator22.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 300));

        jSeparator23.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 10, 300));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Lista de Personas");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(237, 242, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/personas.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Dirección:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombres:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Apellidos:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cédula:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("E-mail:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nº Celular:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jTextFieldDireccion.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDireccion.setBorder(null);
        jTextFieldDireccion.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 260, -1));

        jTextFieldApellidos.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldApellidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldApellidos.setBorder(null);
        jTextFieldApellidos.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 260, -1));

        jTextFieldCedula.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldCedula.setBorder(null);
        jTextFieldCedula.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, -1));

        jTextFieldCorreo.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldCorreo.setBorder(null);
        jTextFieldCorreo.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 260, -1));

        jTextFieldCelular.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldCelular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldCelular.setBorder(null);
        jTextFieldCelular.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, -1));

        jButtonCrearPer.setBackground(new java.awt.Color(237, 242, 244));
        jButtonCrearPer.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonCrearPer.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCrearPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/agregar.png"))); // NOI18N
        jButtonCrearPer.setBorder(null);
        jPanel4.add(jButtonCrearPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 40, 40));

        jButtonEditarPer.setBackground(new java.awt.Color(237, 242, 244));
        jButtonEditarPer.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonEditarPer.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEditarPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/editar.png"))); // NOI18N
        jButtonEditarPer.setBorder(null);
        jPanel4.add(jButtonEditarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 40, 40));

        jButtonLimpiarPer.setBackground(new java.awt.Color(237, 242, 244));
        jButtonLimpiarPer.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonLimpiarPer.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiarPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/limpiar.png"))); // NOI18N
        jButtonLimpiarPer.setBorder(null);
        jPanel4.add(jButtonLimpiarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 50, 40));

        jButtonEliminarPer.setBackground(new java.awt.Color(237, 242, 244));
        jButtonEliminarPer.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonEliminarPer.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEliminarPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/eliminar.png"))); // NOI18N
        jButtonEliminarPer.setBorder(null);
        jPanel4.add(jButtonEliminarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 50, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 260, 10));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 260, 10));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 10));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 260, 10));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 260, 10));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Administración de Personas");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jTextFieldNombres.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldNombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNombres.setBorder(null);
        jTextFieldNombres.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel4.add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, -1));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 260, 10));

        jSeparator17.setBackground(new java.awt.Color(0, 29, 61));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 10));

        jSeparator19.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 500));

        jSeparator27.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 10, 510));

        jSeparator8.setBackground(new java.awt.Color(0, 29, 61));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 360, -1));

        jPanel1.setBackground(new java.awt.Color(237, 242, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Búsqueda de Personas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Opciones de Búsqueda");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 59, -1, -1));

        jTextFieldBusquedaPer.setBackground(new java.awt.Color(237, 242, 244));
        jTextFieldBusquedaPer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldBusquedaPer.setBorder(null);
        jTextFieldBusquedaPer.setPreferredSize(new java.awt.Dimension(74, 25));
        jPanel1.add(jTextFieldBusquedaPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, 205, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 139, 205, 10));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Criterio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 88, -1, -1));

        jButtonBuscarPer.setBackground(new java.awt.Color(237, 242, 244));
        jButtonBuscarPer.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonBuscarPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/buscar.png"))); // NOI18N
        jButtonBuscarPer.setBorder(null);
        jPanel1.add(jButtonBuscarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 108, 38, 37));

        jButtonLimpiarPer1.setBackground(new java.awt.Color(237, 242, 244));
        jButtonLimpiarPer1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonLimpiarPer1.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiarPer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/limpiar.png"))); // NOI18N
        jButtonLimpiarPer1.setBorder(null);
        jButtonLimpiarPer1.setPreferredSize(new java.awt.Dimension(25, 28));
        jPanel1.add(jButtonLimpiarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 108, 43, 37));

        jCheckBoxMostrarTP.setBackground(new java.awt.Color(237, 242, 244));
        jCheckBoxMostrarTP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBoxMostrarTP.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxMostrarTP.setText("Mostrar Todo");
        jCheckBoxMostrarTP.setBorder(null);
        jPanel1.add(jCheckBoxMostrarTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 108, -1, 37));

        jSeparator15.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 10));

        jSeparator16.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 262, 10));

        jSeparator24.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 14, 160));

        jSeparator26.setBackground(new java.awt.Color(0, 29, 61));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 14, 160));

        jSeparator25.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 610, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarPer;
    private javax.swing.JButton jButtonCancelarPersona;
    private javax.swing.JButton jButtonCrearPer;
    private javax.swing.JButton jButtonEditarPer;
    private javax.swing.JButton jButtonEliminarPer;
    private javax.swing.JButton jButtonLimpiarPer;
    private javax.swing.JButton jButtonLimpiarPer1;
    private javax.swing.JCheckBox jCheckBoxMostrarTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTableDatosPersonas;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldBusquedaPer;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombres;
    // End of variables declaration//GEN-END:variables
}
